### PR TITLE
removed the clhep dependency now downloading from gitlab at cern, and removed the data files, these can be added later, and put back later using the commented out cmake portions.

### PR DESCRIPTION
**Pull request by bazinski**

### CODE REVIEW

**Comment by brucellino** [comment]
Can one of the admins verify this patch?

**Comment by bazinski** [comment]
i need this tested, so merged myself :(

**Comment by brucellino** [comment]
@jenkinsSAGrid should test the PR _before_ the merge. Clearly, we're having some issues, so the PR builder didn't get triggered. No stress, I've made hacks like this before... but you know... naughty naughty.

**Comment by bazinski** [comment]
well, i did test the PR locally on the docker containers.

**Pull request merged**
